spring.application.name=starterapp
server.shutdown=graceful

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [%X{requestId:-N/A}] %logger{36} - %msg%n

server.port=8081
